// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Biblioteca.EF.Generate
{
    public partial class Book
    {
        public Book()
        {
            Loan = new HashSet<Loan>();
        }

        public Guid Id { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public int Year { get; set; }

        public virtual ICollection<Loan> Loan { get; set; }
    }
}