// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Biblioteca.EF.Generate
{
    public partial class Client
    {
        public Client()
        {
            Loan = new HashSet<Loan>();
        }

        public Guid Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }

        public virtual ICollection<Loan> Loan { get; set; }
    }
}