// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Biblioteca.EF.Generate
{
    public partial class Loan
    {
        public Guid Id { get; set; }
        public Guid ClientId { get; set; }
        public Guid BookId { get; set; }
        public DateTime LoanDate { get; set; }
        public DateTime? ReturnDate { get; set; }

        public virtual Book Book { get; set; }
        public virtual Client Client { get; set; }
    }
}